### ISSUE TITLE
A lot of option to add.

### ISSUE THREAD

**Issue by bvking** [nickmcintyre/processing-synchronization#5]
Hi Nick,
I have seen your last update of your firefly. And I like to see the light sparking in this little insect.
And I like to see how  the movement organise himself  well.

In my part, I'm trying to render aesthetic as much as possible the entire movement of the coupled oscillators.
That's why I would like you help me to  manage several things:
- Be able to modulate the couple in each case.
- Shift  "naturalfrequencies" one by one. 0 to 1, 1 to 2, ...., 11 to 0.
 And in the other way 0 to 11, 11 to 10 and 1.
- Be able to see the "order parameter" as we could before. I put it again in the library but I can't manage to draw it.

Then, I will have many question to illustrate the movement with sound and maybe you will can help me again.
So it's a big project (motorise this system at a big scale and make sound). I hope you will be interested to develop it again and again ! ;)

I have made of lot of case to vary frequencies and / or phases. 
You can begin a sequence with 0, 9 and c or 1 for example.
Please, try them to find the motion you prefer.

Happy new year!!
[switchfrequencierotatesphere_bis.zip](https://github.com/nickmcintyre/processing-synchronization/files/4098135/switchfrequencierotatesphere_bis.zip)

**Comment by nickmcintyre** [comment]
Very cool sketch, Benjamin! I think adding (overloaded) methods like `setCoupling()` and `shiftFrequency()` would be helpful for common tasks–will tinker a bit.

**Comment by bvking** [comment]
Glad you like it. It encourages me to perfect the project. 
(Smoothen the transitions between the patterns given in the different cases, Try another shape to rotate, do the sound illustration).
Thank you
